#!/bin/bash
# ================================================================
#   VPS COMMUNITY INSTALLER v1.0
#   Self-hosted homelab stack — pick only what you want
#
#   Supported Services:
#     NPM       — Nginx Proxy Manager (SSL + reverse proxy)
#     Nextcloud — Nextcloud AIO (self-hosted cloud storage)
#     Vaultwarden — Bitwarden-compatible password manager
#     Immich    — Self-hosted Google Photos alternative
#     FileBrowser — Web-based file manager
#     Portainer — Docker container management UI
#
#   Target OS : Ubuntu 22.04 / 24.04
#   Author    : Generated by VPS Community Installer Wizard
# ================================================================

# ── Colors + helpers ─────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()  { echo -e "${CYAN}  [INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}  [ OK ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}  [WARN]${NC}  $*"; }
err()   { echo -e "${RED}  [ERR ]${NC}  $*"; exit 1; }
phase() {
  echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BOLD}${CYAN}  $*${NC}"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}
pause()   { read -rp $'\e[33m\n  Press Enter to continue...\e[0m  '; }
ask()     { read -rp "  $1 " "$2"; }
askpass() { read -srp "  $1 " "$2"; echo; }

yesno() {
  # yesno "Question?" VAR  → sets VAR to "y" or "n"
  local reply
  read -rp "  $1 (y/n): " reply
  reply="${reply,,}"
  while [[ "$reply" != "y" && "$reply" != "n" ]]; do
    read -rp "  Please enter y or n: " reply
    reply="${reply,,}"
  done
  printf -v "$2" '%s' "$reply"
}

LOGFILE="$HOME/vps_install_$(date +%F_%H-%M-%S).log"
exec > >(tee -a "$LOGFILE") 2>&1

# ── Guard: do not run as root ────────────────────────────────────
if [ "$EUID" -eq 0 ]; then
  echo -e "${RED}  [ERR] Do not run as root. Run as your normal sudo user.${NC}"
  exit 1
fi

# ================================================================
#   BANNER
# ================================================================
clear
echo -e "${BOLD}${CYAN}"
cat << 'BANNER'

   ██╗  ██╗ ██████╗ ███╗   ███╗███████╗██╗      █████╗ ██████╗
   ██║  ██║██╔═══██╗████╗ ████║██╔════╝██║     ██╔══██╗██╔══██╗
   ███████║██║   ██║██╔████╔██║█████╗  ██║     ███████║██████╔╝
   ██╔══██║██║   ██║██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██╔══██╗
   ██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗███████╗██║  ██║██████╔╝
   ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝

BANNER
echo -e "${NC}${BOLD}  VPS Community Installer v1.0${NC}"
echo    "  Self-hosted homelab stack — you choose what gets installed"
echo
echo -e "${CYAN}  NOTE: Nginx Proxy Manager is always installed — it is required${NC}"
echo -e "${CYAN}        as the SSL gateway and reverse proxy for all services.${NC}"
echo

# ================================================================
#   DNS PRE-FLIGHT CHECK
# ================================================================
echo -e "${RED}${BOLD}  ⚠  STOP — READ THIS BEFORE CONTINUING${NC}"
echo -e "${YELLOW}"
echo "  ALL your service subdomains MUST already have DNS A records"
echo "  pointing to this VPS IP address BEFORE running this script."
echo
echo "  Let's Encrypt SSL verification will FAIL if DNS is not propagated."
echo "  Typical propagation time: 5-30 minutes after setting records."
echo
echo "  TIP: A wildcard record (*.yourdomain.com → VPS IP) covers all"
echo "       subdomains at once and is the easiest approach."
echo -e "${NC}"
read -rp "  My DNS records are set and propagated — ready to continue? (yes/no): " dns_ok
[[ "$dns_ok" != "yes" ]] && { echo "  Set your DNS records first, then re-run."; exit 0; }

# ================================================================
#   SERVICE SELECTION
# ================================================================
phase "STEP 1 — Choose Your Services"
echo
echo "  NPM (Nginx Proxy Manager) is always installed."
echo "  Select which additional services you want:"
echo

yesno "Install Nextcloud AIO?      (self-hosted Google Drive / cloud storage)" WANT_NC
yesno "Install Vaultwarden?        (self-hosted Bitwarden password manager)"   WANT_VAULT
yesno "Install Immich?             (self-hosted Google Photos alternative)"    WANT_IMMICH
yesno "Install FileBrowser?        (web-based file manager for your VPS)"      WANT_FB
yesno "Install Portainer?          (Docker container management dashboard)"    WANT_PORTAINER

echo
echo -e "${BOLD}  Services to install:${NC}"
echo -e "  ${GREEN}✓${NC}  Nginx Proxy Manager (always)"
[[ "$WANT_NC"        == "y" ]] && echo -e "  ${GREEN}✓${NC}  Nextcloud AIO"
[[ "$WANT_VAULT"     == "y" ]] && echo -e "  ${GREEN}✓${NC}  Vaultwarden"
[[ "$WANT_IMMICH"    == "y" ]] && echo -e "  ${GREEN}✓${NC}  Immich"
[[ "$WANT_FB"        == "y" ]] && echo -e "  ${GREEN}✓${NC}  FileBrowser"
[[ "$WANT_PORTAINER" == "y" ]] && echo -e "  ${GREEN}✓${NC}  Portainer"
echo

read -rp "  Confirm service selection? (yes/no): " sel_ok
[[ "$sel_ok" != "yes" ]] && { echo "  Re-run the script to start over."; exit 0; }

# ================================================================
#   WIZARD — Collect configuration
# ================================================================
phase "STEP 2 — Enter Your Configuration"
echo
echo "  Press Enter on any subdomain to accept the default shown in [brackets]."
echo

# ── VPS IP ───────────────────────────────────────────────────────
ask "VPS Public IP Address:" VPS_IP
while [[ -z "$VPS_IP" ]]; do
  warn "VPS IP cannot be empty."
  ask "VPS Public IP Address:" VPS_IP
done

# ── Base domain ──────────────────────────────────────────────────
ask "Base domain (e.g. example.com):" BASE_DOMAIN
while [[ -z "$BASE_DOMAIN" ]]; do
  warn "Domain cannot be empty."
  ask "Base domain:" BASE_DOMAIN
done

# ── Let's Encrypt email ──────────────────────────────────────────
echo
ask "Email for Let's Encrypt SSL certificates:" LE_EMAIL
while [[ -z "$LE_EMAIL" ]]; do
  warn "Email cannot be empty."
  ask "Email for Let's Encrypt SSL:" LE_EMAIL
done

# ── Subdomains ───────────────────────────────────────────────────
echo
echo -e "  ${BOLD}— Subdomains (press Enter to accept default) —${NC}"
ask "NPM admin panel  [npm.$BASE_DOMAIN]:"    NPM_SUB;   NPM_SUB="${NPM_SUB:-npm.$BASE_DOMAIN}"

[[ "$WANT_NC"        == "y" ]] && { ask "Nextcloud        [nc.$BASE_DOMAIN]:"    NC_SUB;    NC_SUB="${NC_SUB:-nc.$BASE_DOMAIN}"; }
[[ "$WANT_VAULT"     == "y" ]] && { ask "Vaultwarden      [vault.$BASE_DOMAIN]:" VAULT_SUB; VAULT_SUB="${VAULT_SUB:-vault.$BASE_DOMAIN}"; }
[[ "$WANT_IMMICH"    == "y" ]] && { ask "Immich           [photos.$BASE_DOMAIN]:" PIC_SUB;  PIC_SUB="${PIC_SUB:-photos.$BASE_DOMAIN}"; }
[[ "$WANT_FB"        == "y" ]] && { ask "FileBrowser      [files.$BASE_DOMAIN]:" FB_SUB;   FB_SUB="${FB_SUB:-files.$BASE_DOMAIN}"; }
[[ "$WANT_PORTAINER" == "y" ]] && { ask "Portainer        [portainer.$BASE_DOMAIN]:" PT_SUB; PT_SUB="${PT_SUB:-portainer.$BASE_DOMAIN}"; }

# ── NPM admin credentials ────────────────────────────────────────
echo
echo -e "  ${BOLD}— NPM Admin Account —${NC}"
ask "NPM admin email:" NPM_EMAIL
while [[ -z "$NPM_EMAIL" ]]; do
  warn "Email cannot be empty."
  ask "NPM admin email:" NPM_EMAIL
done
askpass "NPM admin password:" NPM_PASS
while [[ -z "$NPM_PASS" ]]; do
  warn "Password cannot be empty."
  askpass "NPM admin password:" NPM_PASS
done

# ── Nextcloud country code ───────────────────────────────────────
if [[ "$WANT_NC" == "y" ]]; then
  echo
  ask "2-letter country code for Nextcloud [US]:" COUNTRY_CODE
  COUNTRY_CODE="${COUNTRY_CODE:-US}"
fi

# ── Portainer admin password ─────────────────────────────────────
if [[ "$WANT_PORTAINER" == "y" ]]; then
  echo
  echo -e "  ${BOLD}— Portainer Admin Password —${NC}"
  askpass "Portainer admin password (min 12 chars):" PT_PASS
  while [[ ${#PT_PASS} -lt 12 ]]; do
    warn "Password must be at least 12 characters."
    askpass "Portainer admin password:" PT_PASS
  done
fi

# ================================================================
#   CONFIRMATION SCREEN
# ================================================================
clear
phase "CONFIRM YOUR SETTINGS"
echo
echo -e "  ${BOLD}VPS${NC}"
echo "    IP Address:      $VPS_IP"
echo "    Base Domain:     $BASE_DOMAIN"
echo "    SSL Email:       $LE_EMAIL"
echo
echo -e "  ${BOLD}Services & URLs${NC}"
echo "    NPM Admin:       https://$NPM_SUB"
[[ "$WANT_NC"        == "y" ]] && echo "    Nextcloud:       https://$NC_SUB"
[[ "$WANT_VAULT"     == "y" ]] && echo "    Vaultwarden:     https://$VAULT_SUB"
[[ "$WANT_IMMICH"    == "y" ]] && echo "    Immich:          https://$PIC_SUB"
[[ "$WANT_FB"        == "y" ]] && echo "    FileBrowser:     https://$FB_SUB"
[[ "$WANT_PORTAINER" == "y" ]] && echo "    Portainer:       https://$PT_SUB"
echo
echo -e "  ${BOLD}NPM Admin Login${NC}"
echo "    Email:           $NPM_EMAIL"
echo "    Password:        [hidden]"
echo
read -rp "  Everything correct? Type yes to begin installation (yes/no): " confirm
[[ "$confirm" != "yes" ]] && { echo "  Re-run the script to start over."; exit 0; }

# ================================================================
#   PHASE 1 — System Update + Docker
# ================================================================
phase "PHASE 1 — System Update + Docker"

export DEBIAN_FRONTEND=noninteractive
info "Updating package lists..."
sudo apt-get update -q -o Acquire::http::Timeout=30 -o Acquire::Retries=2

info "Installing required packages..."
PKGS="ca-certificates curl gnupg lsb-release ufw fail2ban iptables git wget unzip jq sqlite3 python3-bcrypt"
sudo apt-get install -y -q $PKGS
ok "System packages installed."

if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
  ok "Docker installed."
  warn "NOTE: You may need to log out and back in if docker commands fail."
  warn "      If so, run: newgrp docker"
  newgrp docker 2>/dev/null || true
else
  ok "Docker already present: $(docker --version)"
fi

# ================================================================
#   PHASE 2 — UFW Firewall
# ================================================================
phase "PHASE 2 — Firewall (UFW)"

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp    comment 'SSH'
sudo ufw allow 80/tcp    comment 'HTTP'
sudo ufw allow 443/tcp   comment 'HTTPS'
sudo ufw allow 81/tcp    comment 'NPM Admin'
[[ "$WANT_NC" == "y" ]] && sudo ufw allow 8080/tcp comment 'Nextcloud AIO Setup'
[[ "$WANT_NC" == "y" ]] && sudo ufw allow 3478/tcp comment 'Nextcloud Talk TCP'
[[ "$WANT_NC" == "y" ]] && sudo ufw allow 3478/udp comment 'Nextcloud Talk UDP'
sudo ufw --force enable
ok "Firewall configured."

# ================================================================
#   PHASE 3 — Docker Network
# ================================================================
phase "PHASE 3 — Docker Network (npm_default)"

if docker network inspect npm_default &>/dev/null; then
  ok "npm_default network already exists."
else
  docker network create npm_default
  ok "npm_default network created."
fi

# ================================================================
#   PHASE 4 — Nginx Proxy Manager
# ================================================================
phase "PHASE 4 — Nginx Proxy Manager"

mkdir -p ~/npm && cd ~/npm

cat > docker-compose.yml << 'NPMEOF'
services:
  npm:
    image: jc21/nginx-proxy-manager:2
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm_net

networks:
  npm_net:
    external: true
    name: npm_default
NPMEOF

docker compose up -d
ok "NPM container started."

# ── Wait for NPM API ─────────────────────────────────────────────
info "Waiting for NPM to be ready (up to 3 minutes)..."
NPM_READY=false
for i in {1..36}; do
  if curl -sf "http://localhost:81/api/" &>/dev/null; then
    NPM_READY=true; break
  fi
  echo -n "."; sleep 5
done
echo
[ "$NPM_READY" = false ] && err "NPM did not start in time. Check: docker logs npm"
ok "NPM is ready."

# ── Seed NPM admin via SQLite ────────────────────────────────────
# NPM v2 does NOT auto-create a default admin — must seed manually.
# The database.sqlite file is root-owned, so sudo sqlite3 is required.
info "Seeding NPM admin user..."
NPM_DB="$HOME/npm/data/database.sqlite"
DB_READY=false
for i in {1..20}; do
  if sudo sqlite3 "$NPM_DB" "SELECT COUNT(*) FROM user;" &>/dev/null; then
    DB_READY=true; break
  fi
  sleep 3
done
[ "$DB_READY" != true ] && err "NPM database not ready. Check: docker logs npm"

USER_COUNT=$(sudo sqlite3 "$NPM_DB" "SELECT COUNT(*) FROM user;")
if [ "$USER_COUNT" -eq "0" ]; then
  NOW=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
  NPM_HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'changeme', bcrypt.gensalt(10)).decode())")

  sudo sqlite3 "$NPM_DB" \
    "INSERT INTO user (created_on,modified_on,is_deleted,email,name,nickname,avatar,roles,is_disabled)
     VALUES ('$NOW','$NOW',0,'admin@example.com','Administrator','Admin','','[\"admin\"]',0);"

  USER_ID=$(sudo sqlite3 "$NPM_DB" "SELECT id FROM user WHERE email='admin@example.com';")

  sudo sqlite3 "$NPM_DB" \
    "INSERT INTO auth (created_on,modified_on,is_deleted,user_id,type,secret,meta)
     VALUES ('$NOW','$NOW',0,$USER_ID,'password','$NPM_HASH','{}');"

  sudo sqlite3 "$NPM_DB" \
    "INSERT INTO user_permission (created_on,modified_on,user_id,visibility,proxy_hosts,redirection_hosts,dead_hosts,streams,access_lists,certificates)
     VALUES ('$NOW','$NOW',$USER_ID,'all','manage','manage','manage','manage','manage','manage');"

  ok "NPM admin user seeded (default: admin@example.com / changeme)."
else
  ok "NPM admin user already exists."
fi

# ── NPM API helpers ──────────────────────────────────────────────
NPM_API="http://localhost:81/api"
NPM_TOKEN=""

npm_auth() {
  NPM_TOKEN=$(curl -sf -X POST "$NPM_API/tokens" \
    -H "Content-Type: application/json" \
    -d "{\"identity\":\"$1\",\"secret\":\"$2\"}" \
    | jq -r '.token // empty')
  [ -n "$NPM_TOKEN" ]
}

npm_add_proxy() {
  local domain="$1" fhost="$2" fport="$3" ws="${4:-false}"
  local body="{\"domain_names\":[\"$domain\"],\"forward_scheme\":\"http\",\"forward_host\":\"$fhost\",\"forward_port\":$fport,\"allow_websocket_upgrade\":$ws,\"access_list_id\":0,\"certificate_id\":\"new\",\"ssl_forced\":true,\"http2_support\":true,\"block_exploits\":true,\"meta\":{\"letsencrypt_email\":\"$LE_EMAIL\",\"letsencrypt_agree\":true,\"dns_challenge\":false}}"
  curl -sf -X POST "$NPM_API/nginx/proxy-hosts" \
    -H "Authorization: Bearer $NPM_TOKEN" \
    -H "Content-Type: application/json" \
    -d "$body" | jq -r '.id // empty'
}

create_proxy() {
  local label="$1" domain="$2" host="$3" port="$4" ws="${5:-false}"
  info "  → $label ($domain)"
  local id
  id=$(npm_add_proxy "$domain" "$host" "$port" "$ws")
  if [ -n "$id" ]; then
    ok "    $domain — proxy #$id created with SSL"
  else
    warn "    $domain — SSL request may have failed; verify in NPM admin panel"
  fi
  sleep 8
}

# ── Authenticate, update credentials, then create proxy hosts ────
info "Authenticating with NPM..."
if npm_auth "admin@example.com" "changeme"; then
  info "Updating NPM admin credentials..."
  curl -sf -X PUT "$NPM_API/users/1" \
    -H "Authorization: Bearer $NPM_TOKEN" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$NPM_EMAIL\",\"nickname\":\"Admin\"}" > /dev/null

  curl -sf -X PUT "$NPM_API/users/1/auth" \
    -H "Authorization: Bearer $NPM_TOKEN" \
    -H "Content-Type: application/json" \
    -d "{\"type\":\"password\",\"current\":\"changeme\",\"secret\":\"$NPM_PASS\"}" > /dev/null

  sleep 2
  npm_auth "$NPM_EMAIL" "$NPM_PASS" || err "Re-auth with new credentials failed."
  ok "NPM credentials updated."
else
  npm_auth "$NPM_EMAIL" "$NPM_PASS" || err "NPM authentication failed. Check: docker logs npm"
  ok "NPM authenticated with existing credentials."
fi

info "Creating proxy hosts + requesting Let's Encrypt SSL certificates..."
warn "This takes about 1 minute per service — please wait..."
echo

create_proxy "NPM Admin"    "$NPM_SUB"   "127.0.0.1" 81    false
[[ "$WANT_NC"        == "y" ]] && create_proxy "Nextcloud"   "$NC_SUB"    "$VPS_IP"                11000 true
[[ "$WANT_VAULT"     == "y" ]] && create_proxy "Vaultwarden" "$VAULT_SUB" "vaultwarden"            80    true
[[ "$WANT_IMMICH"    == "y" ]] && create_proxy "Immich"      "$PIC_SUB"   "immich-server"          2283  true
[[ "$WANT_FB"        == "y" ]] && create_proxy "FileBrowser" "$FB_SUB"    "filebrowser-community"  80    true
[[ "$WANT_PORTAINER" == "y" ]] && create_proxy "Portainer"   "$PT_SUB"    "portainer"              9000  true

ok "NPM proxy hosts configured."

# ================================================================
#   PHASE 5 — Vaultwarden
# ================================================================
if [[ "$WANT_VAULT" == "y" ]]; then
  phase "PHASE 5 — Vaultwarden"

  mkdir -p ~/vaultwarden && cd ~/vaultwarden

  cat > docker-compose.yml << EOF
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - DOMAIN=https://$VAULT_SUB
    volumes:
      - ./vw-data:/data
    expose:
      - "80"
    networks:
      - npm_net

networks:
  npm_net:
    external: true
    name: npm_default
EOF

  docker compose up -d
  ok "Vaultwarden deployed."
fi

# ================================================================
#   PHASE 6 — Immich
# ================================================================
if [[ "$WANT_IMMICH" == "y" ]]; then
  phase "PHASE 6 — Immich"

  mkdir -p ~/immich && cd ~/immich

  IMMICH_DB_PASS=$(openssl rand -hex 16)

  cat > .env << EOF
UPLOAD_LOCATION=./immich-data
DB_DATA_LOCATION=./postgres
TZ=America/New_York
IMMICH_VERSION=release
DB_PASSWORD=$IMMICH_DB_PASS
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_HOSTNAME=database
EOF

  cat > docker-compose.yml << 'IMMICHEOF'
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-server
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    expose:
      - "2283"
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - npm_net
      - immich_internal

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-machine-learning
    volumes:
      - model-cache:/cache
    env_file: .env
    restart: unless-stopped
    networks:
      - immich_internal

  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: immich-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - immich_internal

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: immich-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - immich_internal

networks:
  npm_net:
    external: true
    name: npm_default
  immich_internal:
    internal: true

volumes:
  model-cache:
IMMICHEOF

  docker compose up -d
  ok "Immich deployed."
fi

# ================================================================
#   PHASE 7 — FileBrowser
# ================================================================
if [[ "$WANT_FB" == "y" ]]; then
  phase "PHASE 7 — FileBrowser"

  mkdir -p ~/filebrowser && cd ~/filebrowser
  docker rm -f filebrowser filebrowser-community 2>/dev/null || true
  rm -f filebrowser.db && touch filebrowser.db

  cat > docker-compose.yml << 'FBEOF'
services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: filebrowser-community
    restart: unless-stopped
    user: "0:0"
    expose:
      - "80"
    volumes:
      - /root:/srv
      - ./filebrowser.db:/database/filebrowser.db
    environment:
      - FB_DATABASE=/database/filebrowser.db
    networks:
      - npm_net

networks:
  npm_net:
    external: true
    name: npm_default
FBEOF

  docker compose up -d
  ok "FileBrowser deployed. Default login: admin / admin  (change immediately!)"
fi

# ================================================================
#   PHASE 8 — Portainer
# ================================================================
if [[ "$WANT_PORTAINER" == "y" ]]; then
  phase "PHASE 8 — Portainer"

  mkdir -p ~/portainer && cd ~/portainer

  cat > docker-compose.yml << 'PTEOF'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - npm_net

networks:
  npm_net:
    external: true
    name: npm_default

volumes:
  portainer_data:
PTEOF

  docker compose up -d

  # Set Portainer admin password via API
  info "Waiting for Portainer to be ready..."
  for i in {1..12}; do
    if curl -sf "http://localhost:9000/api/status" &>/dev/null; then break; fi
    sleep 5
  done

  curl -sf -X POST "http://localhost:9000/api/users/admin/init" \
    -H "Content-Type: application/json" \
    -d "{\"Username\":\"admin\",\"Password\":\"$PT_PASS\"}" > /dev/null \
    && ok "Portainer admin password set." \
    || warn "Portainer password init failed — set it manually on first visit to https://$PT_SUB"

  ok "Portainer deployed."
fi

# ================================================================
#   PHASE 9 — Nextcloud AIO  (requires one manual step)
# ================================================================
if [[ "$WANT_NC" == "y" ]]; then
  phase "PHASE 9 — Nextcloud AIO"

  mkdir -p ~/nextcloud-aio && cd ~/nextcloud-aio

  cat > docker-compose.yml << 'NCEOF'
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
NCEOF

  docker compose up -d
  ok "Nextcloud AIO master container started."

  echo
  echo -e "${YELLOW}${BOLD}"
  echo "  ┌──────────────────────────────────────────────────────────┐"
  echo "  │         MANUAL STEP — NEXTCLOUD INITIAL SETUP           │"
  echo "  │   (This is the only step that cannot be automated)      │"
  echo "  └──────────────────────────────────────────────────────────┘"
  echo -e "${NC}${YELLOW}"
  echo "  1. Open in your browser:   http://$VPS_IP:8080"
  echo "  2. Enter your domain:      $NC_SUB"
  echo "  3. Click 'Start containers' and wait for setup to complete."
  echo "  4. Wait until the page shows: 'Initial setup is complete'"
  echo "  5. Come back here and press Enter to continue."
  echo -e "${NC}"
  pause

  info "Applying Nextcloud post-install fixes..."
  docker exec --user www-data nextcloud-aio-nextcloud \
    php occ config:system:set default_phone_region --value="$COUNTRY_CODE" 2>/dev/null \
    || warn "OCC region fix skipped — Nextcloud may still be initializing."
  docker exec --user www-data nextcloud-aio-nextcloud \
    php occ maintenance:repair --include-expensive 2>/dev/null || true
  ok "Nextcloud post-install fixes applied."
fi

# ================================================================
#   PHASE 10 — Fail2Ban (Docker-aware)
# ================================================================
phase "PHASE 10 — Fail2Ban"

sudo tee /etc/fail2ban/action.d/docker-action.conf > /dev/null << 'F2BEOF'
[Definition]
actionstart = iptables -N f2b-<name>
              iptables -A f2b-<name> -j RETURN
              iptables -I INPUT -j f2b-<name>
              iptables -I DOCKER-USER -j f2b-<name>
actionstop  = iptables -D DOCKER-USER -j f2b-<name>
              iptables -D INPUT -j f2b-<name>
              iptables -F f2b-<name>
              iptables -X f2b-<name>
actioncheck = iptables -n -L INPUT | grep -q 'f2b-<name>[ \t]'
actionban   = iptables -I f2b-<name> 1 -s <ip> -j DROP
actionunban = iptables -D f2b-<name> -s <ip> -j DROP
F2BEOF

sudo tee /etc/fail2ban/filter.d/npm-docker.conf > /dev/null << 'F2BEOF'
[Definition]
failregex = ^<HOST> .+ "(GET|POST|HEAD) .+ HTTP/.*" (400|401|403|444) .+$
ignoreregex =
F2BEOF

sudo tee /etc/fail2ban/jail.local > /dev/null << 'F2BEOF'
[DEFAULT]
bantime  = 86400
findtime = 600
maxretry = 3
banaction = docker-action

[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 3

[npm-docker]
enabled  = true
port     = http,https
filter   = npm-docker
logpath  = /root/npm/data/logs/proxy-host-*_access.log
maxretry = 15
F2BEOF

sudo systemctl enable fail2ban
sudo systemctl restart fail2ban
ok "Fail2Ban configured."

# ================================================================
#   FINAL SUMMARY
# ================================================================
clear
echo -e "${GREEN}${BOLD}"
echo "  ╔══════════════════════════════════════════════════════════╗"
echo "  ║                                                        ║"
echo "  ║          INSTALLATION COMPLETE!                        ║"
echo "  ║                                                        ║"
echo "  ╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "${BOLD}  Your Services:${NC}"
echo
echo -e "  ${GREEN}✓${NC}  NPM Admin Panel  →  https://$NPM_SUB"
[[ "$WANT_NC"        == "y" ]] && echo -e "  ${GREEN}✓${NC}  Nextcloud        →  https://$NC_SUB"
[[ "$WANT_VAULT"     == "y" ]] && echo -e "  ${GREEN}✓${NC}  Vaultwarden      →  https://$VAULT_SUB"
[[ "$WANT_IMMICH"    == "y" ]] && echo -e "  ${GREEN}✓${NC}  Immich           →  https://$PIC_SUB"
[[ "$WANT_FB"        == "y" ]] && echo -e "  ${GREEN}✓${NC}  FileBrowser      →  https://$FB_SUB"
[[ "$WANT_PORTAINER" == "y" ]] && echo -e "  ${GREEN}✓${NC}  Portainer        →  https://$PT_SUB"
echo
echo -e "${BOLD}  First-Login Defaults (change these immediately!):${NC}"
echo "    NPM Admin:     $NPM_EMAIL / [your password]"
[[ "$WANT_FB"        == "y" ]] && echo "    FileBrowser:   admin / admin"
[[ "$WANT_IMMICH"    == "y" ]] && echo "    Immich:        Create your account on first visit"
[[ "$WANT_NC"        == "y" ]] && echo "    Nextcloud:     Created during the setup wizard above"
[[ "$WANT_PORTAINER" == "y" ]] && echo "    Portainer:     admin / [your password]"
echo
echo -e "${BOLD}  Docker Network:${NC} npm_default  (all containers joined)"
echo -e "${BOLD}  Log file:${NC}       $LOGFILE"
echo
echo -e "${BOLD}  To add a new service later — use this pattern:${NC}"
echo
echo "    mkdir ~/myservice && cd ~/myservice"
cat << 'TIPEOF'
    # docker-compose.yml:
    # services:
    #   myservice:
    #     image: some/image:latest
    #     container_name: myservice
    #     restart: unless-stopped
    #     expose:
    #       - "PORT"           # never use ports: — NPM handles external access
    #     networks:
    #       - npm_net
    # networks:
    #   npm_net:
    #     external: true
    #     name: npm_default    # THE key — must match this exactly
TIPEOF
echo
echo "    docker compose up -d"
echo "    # Then add a proxy host in NPM at https://$NPM_SUB"
echo
echo -e "${GREEN}${BOLD}  All done! Enjoy your self-hosted homelab.${NC}"
echo
